spring:
  datasource:
    departments:
      username: root
      jdbc-url: jdbc:mysql://localhost:3307/departments
      password: pass
    courses:
      jdbc-url: jdbc:mysql://localhost:3307/courses
      username: root
      password: pass
