spring:
  output:
    ansi:
      enabled: ALWAYS
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 10
        max-page-size: 500
management:
  endpoints:
    web:
      exposure:
        include: "*"
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
server:
  port: '8080'
